### UI
GET {{host}}/ui

### Get controller schedules
GET {{host}}/controllers/schedules

### Get customer details
GET {{host}}/customers/details

### Run zone
POST {{host}}/zones/{{zone_id}}?run_time=60

### Stop zone
DELETE {{host}}/zones/{{zone_id}}
